# Generated by Django 4.2.5 on 2023-10-08 07:47

import django.core.validators
from django.db import migrations, models
import personal.models
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enteghad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20, verbose_name='کاربر')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان انتقاد')),
                ('descriptions_user', models.TextField(blank=True, default='', null=True, verbose_name='توضیحات کاربر')),
                ('descriptions_admin', models.TextField(blank=True, default='', null=True, verbose_name='نوضیحات مدیریت')),
            ],
            options={
                'verbose_name': 'انتقاد و پیشنهاد',
                'verbose_name_plural': 'انتقاد و پیشنهادها',
            },
        ),
        migrations.CreateModel(
            name='Mali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20, verbose_name='کاربر')),
                ('descriptions_user', models.TextField(blank=True, default='', null=True, verbose_name='توضیحات کاربر')),
                ('descriptions_admin', models.TextField(blank=True, default='', null=True, verbose_name='نوضیحات مدیریت')),
                ('etebar', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000), django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='میزان درخواست اعتبار (تومان)')),
                ('type', models.CharField(choices=[('bedehkar', 'بدهکار'), ('bestankar', 'بستانکار')], max_length=200, verbose_name='نوع درخواست')),
                ('taeed_activity', models.BooleanField(default=False, verbose_name='وضعیت تایید')),
                ('tasvie_activity', models.BooleanField(default=False, verbose_name='وضعیت تسویه')),
            ],
            options={
                'verbose_name': 'اعتبار',
                'verbose_name_plural': 'اعتبار',
            },
        ),
        migrations.CreateModel(
            name='Morkhasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=20, verbose_name='کاربر')),
                ('descriptions_user', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='توضیحات کاربر')),
                ('descriptions_admin', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='نوضیحات مدیریت')),
                ('start_date', models.DateField(default=personal.models.tomorrowDate, verbose_name='تاریخ شروع مرخصی')),
                ('end_date', models.DateField(default=personal.models.tomorrowDate, verbose_name='تاریخ پایان مرخصی')),
                ('active', models.BooleanField(default=False, verbose_name='تایید مرخصی')),
            ],
            options={
                'verbose_name': 'مرخصی',
                'verbose_name_plural': 'درخواست مرخصی',
            },
        ),
    ]
