# Generated by Django 4.2.5 on 2023-10-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import samane.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30, verbose_name='عنوان رشته')),
                ('descriptions', models.CharField(blank=True, max_length=100, null=True, verbose_name='توضیحات رشته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('descriptions', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='نوضیحات')),
                ('date_report', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد گزارش')),
                ('date_upload', models.DateTimeField(auto_now_add=True, verbose_name='زمان بارگذاری')),
                ('documents', models.FileField(default='', null=True, upload_to=samane.models.user_directory_path, verbose_name='بارگزاری سند')),
                ('user', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='کاربر ')),
                ('slug', models.SlugField(verbose_name='آدرس مقاله')),
                ('author', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده گزارش')),
                ('topic', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.RESTRICT, to='samane.topic', verbose_name='موضوع')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
            },
        ),
    ]
